### ISSUE TITLE
KeyError:  about "Can't find linking activity for exchange"

### ISSUE THREAD

**Issue by MMahdi97** [polca/premise#174]
I have run the following code: 
```
from premise import *
import bw2data
from datapackage import Package
import brightway2 as bw
    
bw2data.projects.set_current("test2")    
    
fp = r"Z:\Uni-LUT\Thesis\Code\Hydrogen example\datapackage.json"
hydrogen = Package(fp)


external_scenarios = [
    {"scenario": "Ambitious", "data": hydrogen},
]



ndb = NewDatabase(
            scenarios = [
                {"model":"remind", "pathway":"SSP2-PkBudg1150", "year":2030, "external scenarios": external_scenarios},
                {"model":"remind", "pathway":"SSP2-PkBudg1150", "year":2050, "external scenarios": external_scenarios},
           ],           
            source_type="ecospold", # <--- this is NEW
            source_file_path=r"C:\Users\z132387\Ecoinvent39_cut_off\ecoinvent 3.9_cutoff_ecoSpold02\datasets", # <-- this is NEW
            source_version="3.9",
            key='tUePmX_S5B8ieZkkM7WUU2CnO8SmShwmAeWK9x2rTFo=',
)


ndb.update([
    "external"
])

ndb.write_db_to_brightway()
```

and I have this error:
```

ndb.write_db_to_brightway()
Write new database(s) to Brightway.
Running all checks...
Minor anomalies found: check the change report.
---> MAJOR anomalies found: check the change report.
Traceback (most recent call last):

  File C:\ProgramData\Anaconda3\envs\bw\lib\site-packages\wurst\linking.py:28 in link_internal
    exc["input"] = products[get_tuple(exc)]

  File C:\ProgramData\Anaconda3\envs\bw\lib\site-packages\wurst\linking.py:12 in <lambda>
    get_tuple = lambda exc: tuple([exc[f] for f in fields])

  File C:\ProgramData\Anaconda3\envs\bw\lib\site-packages\wurst\linking.py:12 in <listcomp>
    get_tuple = lambda exc: tuple([exc[f] for f in fields])

KeyError: 'product'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  Cell In[5], line 1
    ndb.write_db_to_brightway()

  File ~\AppData\Roaming\Python\Python310\site-packages\premise\new_database.py:1062 in write_db_to_brightway
    write_brightway_database(

  File ~\AppData\Roaming\Python\Python310\site-packages\premise\brightway2.py:46 in write_brightway_database
    link_internal(data)

  File C:\ProgramData\Anaconda3\envs\bw\lib\site-packages\wurst\linking.py:30 in link_internal
    raise KeyError(

KeyError: "Can't find linking activity for exchange:\n{'amount': 0.8171603677221655,\n 'location': 'RoW',\n 'name': 'industrial gases production, cryogenic air separation',\n 'type': 'technosphere',\n 'unit': 'kilogram'}"
```

Could someone help me with this issue, please?

**Comment by romainsacchi** [comment]
I understand that you are now using a development version. That means it may contain errors.
That being said, I'm releasing `2.1.1.dev5` which should be available in about half an hour and should fix that issue.

**Comment by MMahdi97** [comment]
@romainsacchi Thank you Romaon, 
I think the new version has been released now. Could you please tell me how to use this new version?

**Comment by romainsacchi** [comment]
Yes, you need to update the library and restart your kernel.

**Comment by MMahdi97** [comment]
@romainsacchi I have updated all the libraries in my working environment which is "bw" and restarted the kernel in Spyder, but I still have the same error!
Here you can see that all the libraries have been updated
![image](https://github.com/user-attachments/assets/6153fc86-4305-40cf-87b2-13b0698ff743)

here is the error again:
```

ndb.write_db_to_brightway()
Write new database(s) to Brightway.
Running all checks...
Minor anomalies found: check the change report.
---> MAJOR anomalies found: check the change report.
Traceback (most recent call last):

  File C:\ProgramData\Anaconda3\envs\bw\lib\site-packages\wurst\linking.py:28 in link_internal
    exc["input"] = products[get_tuple(exc)]

  File C:\ProgramData\Anaconda3\envs\bw\lib\site-packages\wurst\linking.py:12 in <lambda>
    get_tuple = lambda exc: tuple([exc[f] for f in fields])

  File C:\ProgramData\Anaconda3\envs\bw\lib\site-packages\wurst\linking.py:12 in <listcomp>
    get_tuple = lambda exc: tuple([exc[f] for f in fields])

KeyError: 'product'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  Cell In[2], line 1
    ndb.write_db_to_brightway()

  File ~\AppData\Roaming\Python\Python310\site-packages\premise\new_database.py:1062 in write_db_to_brightway
    write_brightway_database(

  File ~\AppData\Roaming\Python\Python310\site-packages\premise\brightway2.py:46 in write_brightway_database
    link_internal(data)

  File C:\ProgramData\Anaconda3\envs\bw\lib\site-packages\wurst\linking.py:30 in link_internal
    raise KeyError(

KeyError: "Can't find linking activity for exchange:\n{'amount': 0.8171603677221655,\n 'location': 'RoW',\n 'name': 'industrial gases production, cryogenic air separation',\n 'type': 'technosphere',\n 'unit': 'kilogram'}"
```

**Comment by romainsacchi** [comment]
You need to print `conda list` for us to see all libraries. `premise` should be `2.1.1.dev5`.

> I have updated all the libraries in my working environment which is "bw"
You just need to update `premise`, not `bw_xxxx` libraries.

**Comment by MMahdi97** [comment]
@romainsacchi I have used these four to update `premise` : `conda update premise`, `conda update premise==2.1.1.dev5`, `conda install premise==2.1.1.dev5 `, and `conda install premise==2.1.1`, here are the results of each of them:

![image](https://github.com/user-attachments/assets/620a5209-a954-45f1-bfcf-e05773e96056)
![image](https://github.com/user-attachments/assets/f3e281cf-0421-4fe2-9b8e-7b9375652d97)
![image](https://github.com/user-attachments/assets/d2501a34-b47d-4551-84be-786332677fb4)
![image](https://github.com/user-attachments/assets/b8c6e8a6-9e32-4894-a018-4e192cb550b6)

but when I print `conda list`, `premise `is still `2.1.0`

![image](https://github.com/user-attachments/assets/4e5ef028-5f20-4c65-a57a-76b3e6b7b5ae)

I tried all the possible ways to update it. Am I doing something wrong? Why can't I update it?

**Comment by romainsacchi** [comment]
Because the development versions are not available on conda under this semantic. Instead, they are dated
If you use conda, you can do `conda install premise`.

**Comment by MMahdi97** [comment]
I did what you said, but nothing changed!
![image](https://github.com/user-attachments/assets/f56d786b-8ef6-45f8-85f5-257462ebcac5)
version is still 2.1.0
![image](https://github.com/user-attachments/assets/d9d8eb9f-99ec-409b-a3e3-8d74544a8b6d)

However, when I run the code it is written version 2.1.1.dev4 not dev5
![image](https://github.com/user-attachments/assets/62323e59-e114-43c5-af70-50cf4e43a85a)

**Comment by romainsacchi** [comment]
You can try to specify the wanted version. ALso, have you specified the correct channel? e.g., `conda install romainsacchi::premise==2024.07.25`

**Comment by MMahdi97** [comment]
I used ` conda install romainsacchi::premise==2024.07.25`, and the channel has changed:

![image](https://github.com/user-attachments/assets/e7b7b4f4-d5ad-4751-8089-217e7f210616)

but when I run the code it is still written:
![image](https://github.com/user-attachments/assets/dd887047-90c0-4fe9-a4ff-6caf4b0c7b22)

And I still have the error!
![image](https://github.com/user-attachments/assets/ee5e98f2-ad86-44e4-9677-5d7702d3e079)

**Comment by MMahdi97** [comment]
I also tried to specify the version I want with `conda install premise==2.1.1.dev5`
But here is the result:
![image](https://github.com/user-attachments/assets/43154d5e-30ef-432b-811e-82a9484f1f39)

**Comment by romainsacchi** [comment]
I think you probably have at this point an issue with the conda environment.
It says `2.1.1.dev5` is installed, but uses `2.1.1.dev4`.
I suggest you delete that tone and create a new one, installing directly `2.1.1.dev5`.

**Comment by romainsacchi** [comment]
As I said, using conda, you cannot specify the version like `2.1.1.dev5`, as it uses dates in this case -- see[ file history](https://anaconda.org/romainsacchi/premise).

**Comment by MMahdi97** [comment]
As you suggested, I removed `premise `and installed it again, but it is still using `2.1.1.dev4` version.

![image](https://github.com/user-attachments/assets/44f56cf4-9508-43f6-9872-12e43152283f)
![image](https://github.com/user-attachments/assets/5a161a54-9939-4508-8b52-3513ad083cd3)

I checked the[ file history](https://anaconda.org/romainsacchi/premise/files) you mentioned, and I downloaded the last version. I don't know if it is related or not, but in the file it is written:
![image](https://github.com/user-attachments/assets/a9781048-440c-40a5-a335-f3e47f4f9056)

I also downloaded the file you released yesterday in that file the version is 2.1.1.dev5
![image](https://github.com/user-attachments/assets/c1a701db-913c-4652-83a4-09cfc2f3b46b)

I think something happened when you released the new version today. Could you please check it?

**Comment by romainsacchi** [comment]
I did not suggest removing `premise` and re-installing it. I suggested deleting this Conda environment and re-creating it. It is different.

But regarding the above, this is because conda is used for day-to-day development purposes (I made a change to a parallel branch which got uploaded to conda). In any case, I think you need to use the latest stable version, not the development version, that is `2.1.0`. So, in a fresh conda environment, do `pip install premise==2.1.0`.

**Comment by romainsacchi** [comment]
Re-open if the issue isn't solved.
