### ISSUE TITLE
Linking issues in `2.3.0.dev1_intervs`

### ISSUE THREAD

**Issue by dbantje** [polca/premise#231]
Hi,

I'm getting again linking issues with the above premise version (after clearing database and inventory cache):

Firstly, I get the message:

```
Could not find a biosphere flow for ('Sodium hydroxide', 'water', 'unspecified', 'kilogram') or ('Sodium hydroxide', 'water', 'unspecified', 'kilogram') in lci-hydrogen-electrolysis.xlsx. Exchange deleted.
Could not find a biosphere flow for ('Sodium hydroxide', 'water', 'unspecified', 'kilogram') in lci-hydrogen-electrolysis.xlsx. You need to fix this.
Could not find a biosphere flow for ('Sodium hydroxide', 'water', 'unspecified', 'kilogram') or ('Sodium hydroxide', 'water', 'unspecified', 'kilogram') in lci-hydrogen-electrolysis.xlsx. Exchange deleted.
Could not find a biosphere flow for ('Sodium hydroxide', 'water', 'unspecified', 'kilogram') in lci-hydrogen-electrolysis.xlsx. You need to fix this.
```

There's then a bunch of warning on missing classification, and the code fails on the following unlinked exchanges:

```
List of unlinked exchanges:
+------------------------------------------------------------------------+-------------------------------------------------------------+----------------------------+------------+---------------+--------------+----------------------------------+
|                                  Name                                  |                      Reference product                      |          Location          | Categories |      Unit     |     Type     |               File               |
+------------------------------------------------------------------------+-------------------------------------------------------------+----------------------------+------------+---------------+--------------+----------------------------------+
|          market for transport, freight, train, fleet average           |           transport, freight, train, fleet average          | Europe without Switzerland |    None    | ton kilometer | technosphere | lci-wind-turbine-magnet-eol.xlsx |
| market for transport, freight, lorry, 16-32 metric ton, diesel, EURO 3 | transport, freight, lorry, 16-32 metric ton, diesel, EURO 3 |            RER             |    None    | ton kilometer | technosphere | lci-wind-turbine-magnet-eol.xlsx |
|  market for transport, freight, lorry, >32 metric ton, diesel, EURO 3  |  transport, freight, lorry, >32 metric ton, diesel, EURO 3  |            RER             |    None    | ton kilometer | technosphere | lci-wind-turbine-magnet-eol.xlsx |
+------------------------------------------------------------------------+-------------------------------------------------------------+----------------------------+------------+---------------+--------------+----------------------------------+
```

**Comment by romainsacchi** [comment]
I think this could be @alvarojhahn 's recent additions of EoL datasets.

**Comment by alvarojhahn** [comment]
I have updated classification.xlsx and migration_map.csv

The workflow should work now with EI310 in addition to EI311.

################

Regarding the emissions of Sodium Hydroxide to water, this compartment is not available previous to EI3.10. @romainsacchi  is it okay to just drop the environmental flow in the new LCI?

**Comment by dbantje** [comment]
Hey @alvarojhahn,

I again get the same errors with the current `2.3.0.dev1_intervs`.

**Comment by alvarojhahn** [comment]
Hi @dbantje ,

I did a fresh installation of 2.3.0.dev1_intervs and I get no missing classifications and no errors (ie, no unlinked exchanges from "lci-wind-turbine-magnet-eol.xlsx"), both working with ei3.10.1 and 3.11.

Regarding the missing biosphere flows, which are not blocking issues, ei3.11 works fine. And there are two missing biosphere flows for ei3.10.1:

- sodium hydroxide
- phosphine.

However, this does not prevent us from running the premise update and writing the database.

Regarding phosphine, it is present in an inventory but it is set to 0. So no problem there.

Regarding the emissions of Sodium Hydroxide to water, this compartment is not available previous to EI3.11. @romainsacchi is it okay to just drop the environmental flow in the new LCI, as premise is doing now?

@dbantje , are you getting any additional error?

**Comment by dbantje** [comment]
Hi! It could actually be because I was using ei3.10, not ei3.10.1. I will test and report back!

**Comment by dbantje** [comment]
Hi @alvarojhahn!

Unfortunately, I still get errors. During importing, I get the linking errors for sodium hydroxide and phosphine, as you said. What ultimately makes the code fail is the `Electricity` validation:

<img width="1570" height="545" alt="Image" src="https://github.com/user-attachments/assets/31d6b0d8-13c3-47f6-8df2-c2f002e00ca8" />

I'm using ecoinvent 3.10.1, and this branch: https://github.com/dbantje/premise/tree/interventionpaper_v4, which is just `2.3.0.dev1_intervs` plus the following two commits:
- commit d37cbd9 (changes the capacity mapping)
- commit 975b11b (just downloaded IAM files)
I don't see how these two would the lead to the errors, so I'm quite confused why I still get them.

**Comment by romainsacchi** [comment]
Hi @dbantje, ok, I'll look at it and get back to you.

**Comment by romainsacchi** [comment]
Hi @dbantje, I updated the migration_map.csv file to avoid the issues you're seeing with unliked exchanges. I could run without issues after that. Hence, update [your own version of migration_map.csv](https://github.com/dbantje/premise/blob/interventionpaper_v4/premise/data/additional_inventories/migration_map.csv) with [that one](https://github.com/polca/premise/blob/master/premise/data/additional_inventories/migration_map.csv).

**Comment by romainsacchi** [comment]
<img width="614" height="481" alt="Image" src="https://github.com/user-attachments/assets/0a0c5f48-86fe-4c8b-be07-0d3234f70337" />

**Comment by dbantje** [comment]
Seems to be an issue with our cluster (or how our cluster accesses the conda environment), but it works on the login node ... Thanks!
